FROM python:3.9-slim

# Install necessary system dependencies
RUN apt-get update && apt-get install -y python3-distutils

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy your Streamlit app
COPY . /app
WORKDIR /app

# Run Streamlit
CMD ["streamlit", "run", "Streamlit.py"]
